import Head from "next/head";
import { Open_Sans } from "next/font/google";
import { HvDropdown } from "@hitachivantara/uikit-react-core";

const openSans = Open_Sans({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${openSans.className}`}>
        <HvDropdown
          defaultExpanded
          label="Select values"
          multiSelect
          showSearch
          status="valid"
          values={[
            {
              label: "value 1",
            },
            {
              label: "value 2",
              selected: true,
            },
            {
              label: "value 3",
            },
            {
              label: "value 4",
            },
          ]}
        />
      </main>
    </>
  );
}
